### ISSUE TITLE
Multiple onvif supported IP cameras connected to one NVR

### ISSUE THREAD

**Issue by Aravinthleader** [onvif/testspecs#37] opened 2022-06-24 10:50 UTC
Hi,
I have 36 cameras connected to a switch and NVR . While clicking the search button in the NVR menu, we are supposed to get all the cameras to be listed in the NVR. But we are only getting nearly 25 cameras listed and the count is random. When clicking the search button again it shows / listing 30 cameras. The count range is changing between 25 to 32 out of 36 cameras.What could be the reason for this issue ?

Thanks in advance.

**Comment by baldvin137** [comment] 2022-08-04 11:48
Hi, 

Did you figure out what the problem was? 

One possibility could be that the devices have not implemented the recommended random response time to probe requests, or that the NVR is not expecting such a delay in the response. 
See http://docs.oasis-open.org/ws-dd/discovery/1.1/os/wsdd-discovery-1.1-spec-os.html#_Toc234231819

We had this issue in the Device Test Tool many years ago, that it was not expecting that the response might be delayed by the device. This random delay is done to avoid network storming as a result of every device on the network responding to the discovery probe. If the devices do not implement this and all respond at once, then the NVR might not be able to handle all answers at once and some may get lost as it is UDP.

**Comment by baldvin137** [comment] 2022-08-15 11:25
Duplicate of https://github.com/onvif/specs/issues/226

**Closed** 2022-08-15 11:25 UTC
Labels: duplicate
