### ISSUE TITLE
Multiple IPv6 tests have a "Switching to IPv6 address" step which does not consider URI scheme

### ISSUE THREAD

**Issue by kumaakh** [onvif/testspecs#72] opened 2024-02-16 05:44 UTC
ONVIF TT 23.06.96
Consider any of the following tests:

- RTSS-1-1-54-v21.12 MEDIA STREAMING – JPEG (RTP-Unicast/UDP, IPv6)
- RTSS-1-1-55-v21.06 MEDIA STREAMING - JPEG (RTP-Unicast/RTSP/HTTP/TCP, IPv6)
- RTSS-1-1-56-v21.06 MEDIA STREAMING – JPEG (RTP/RTSP/TCP, IPv6)
- RTSS-1-1-60-v21.12 MEDIA STREAMING - H.264 (RTP-Unicast/UDP, IPv6)
- RTSS-1-1-61-v21.06 MEDIA STREAMING - H.264 (RTP-Unicast/RTSP/HTTP/TCP, IPv6)
- RTSS-1-1-62-v21.06 MEDIA STREAMING - H.264 (RTP/RTSP/TCP, IPv6)

 (there may be more) 
 
 All of them have this pattern:

1. Get Network interfaces to know about the IPv4 and IPv addresses of the device 
2. Swith to IPv6 address, here ONVIF TT tries to construct the service URI on it's own but while switching to IPv6 the URI scheme is ignored as shown below

   STEP 6 - Switching to IPv6 address
      StepStart: 2024-02-15T22:48:18.6912965Z
      Old address https://192.168.1.163/onvif/device_service
      Selecting http://[fe80::c29b:f4ff:fe90:37]/onvif/device_service
   STEP PASSED
   
Notice how the client changes an https://IPv4/ (SSL) address to an http://IPv6 (non SSL) address. 

A secure device would not accpet the http://IPv6/ address and the test fails. 

### VERY IMPORTANT:
the same "Switch to IPv6 address" step works fine in the following case

MEDIA2_RTSS-1-1-6-v21.06 MEDIA2 STREAMING – H.264 (RTP-Unicast/RTSP/HTTP/TCP, IPv6)
MEDIA2_RTSS-1-1-7-v21.06 MEDIA2 STREAMING – H.264 (RTP/RTSP/TCP, IPv6)
MEDIA2_RTSS-1-1-17-v21.06 MEDIA2 STREAMING – H.264 (RTP-Unicast/RTSP/HTTPS/TCP, IPv6)
MEDIA2_RTSS-1-2-2-v21.06 MEDIA2 STREAMING – H.264 (RTP-Multicast, IPv6)
and many more Media2 streaming cases related to IPv6

   STEP 6 - Switching to IPv6 address
      StepStart: 2024-02-13T12:41:42.2662214Z
      Old address https://172.16.1.215/onvif/device_service
      Selecting https://[2600:1700:87f0:9cff:c29b:f4ff:fe90:60d]:443/onvif/device_service
   STEP PASSED

This shows an incosistency in the ONVIF client's behaviour hence this Bug Report

**Comment by madhurao68** [comment] 2024-02-21 13:49
We have assigned this to our tool vendor and shall respond as soon as we get a response. Thanks for your patience!

**Comment by madhurao68** [comment] 2024-03-29 06:03
It appears that the device supports only HTTPS (and does not support HTTP) and you are facing this issue when you are trying to pass conformance with a device that supports HTTPS configuration.

The problem is that the DTT doesn't support conformance over HTTPS. HTTPS is supported by some tests, however the tool is not designed to pass conformance over HTTPS.

**Comment by kumaakh** [comment] 2024-03-29 13:40
Yes I understood that. 
However the approach of switching to a wrong URI scheme seems like a bug in the tests specially because there is another set of tests which do it correctly.

**Comment by madhurao68** [comment] 2024-04-03 12:48
We are currently not sure if the devices which do not support http are conformant since profiles require streaming over HTTP:

![image](https://github.com/onvif/testspecs/assets/73811069/ad534106-588d-4ec5-ae86-78cd907f02f5)

Some tests may work with https, but it is not required to work with https, so some tests do not support this possibility.

**Closed as completed** 2024-06-12 13:30 UTC
