### ISSUE TITLE
 MEDIA-6-1-1  5.5.1 SNAPSHOT URI  with https scheme

### ISSUE THREAD

**Issue by kumaakh** [onvif/testspecs#71] opened 2024-02-16 05:22 UTC
ONVIF TT version 23.06 rev 96

MEDIA-6-1-1-v20.06 SNAPSHOT URI
Both the above tests fails when the device is in secure mode, test execution script attached below. 

Step 6: GetSnapshotUri is called and the following URI is provided
https://IP:443/<path>
Step 7 and 8 pass (valid URI)
Step 9 fails with following

STEP 9 - Invoke HTTP GET request on snapshot URI
      StepStart: 2024-02-16T05:00:14.1201672Z
      The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
STEP FAILED

Note: 
1. All previous SSL exchanges were correctly initiated by client, so why not this one ?
2.  The provided https:// Image URI opens fine in chrome etc. with keys exchange and authentication
3. The same test passes fine when device is serving in non-SSL mode.

Log of this test attached below
[SnapLog.txt](https://github.com/onvif/testspecs/files/14306183/SnapLog.txt)

The same issue applies to 
MEDIA2-5-1-1-v20.12 SNAPSHOT URI and

**Comment by madhurao68** [comment] 2024-02-21 13:49
We have assigned this to our tool vendor and shall respond as soon as we get a response. Thanks for your patience!

**Comment by madhurao68** [comment] 2024-11-12 20:37
The problem is that the DTT doesn't support conformance over HTTPS, we initially didn't have such goal.

**Comment by kumaakh** [comment] 2024-11-12 20:46
@madhurao68 will this be fixed in a new version. The device behaviour is not wrong

**Comment by madhurao68** [comment] 2024-11-12 21:42
You will need to execute conformance over HTTP and not HTTPS.

**Closed as completed** 2024-12-02 02:26 UTC
